class UseTermService {

    constructor() { };

    useTerm = () => {return (`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Pellentesque id nibh tortor id aliquet lectus proin. In hac habitasse platea dictumst vestibulum rhoncus est. Lacinia quis vel eros donec ac odio tempor orci dapibus. Eget gravida cum sociis natoque penatibus et magnis. Facilisis volutpat est velit egestas dui id ornare. Aliquam etiam erat velit scelerisque in. Sodales ut eu sem integer vitae justo eget. Tincidunt eget nullam non nisi est sit amet facilisis magna.

    Cursus in hac habitasse platea dictumst quisque. Augue ut lectus arcu bibendum at varius vel pharetra. Scelerisque purus semper eget duis at tellus at urna. Urna nec tincidunt praesent semper. Adipiscing bibendum est ultricies integer. Non consectetur a erat nam at lectus urna duis convallis. Convallis aenean et tortor at risus. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Et tortor consequat id porta nibh venenatis cras sed felis. Donec pretium vulputate sapien nec sagittis. Nunc id cursus metus aliquam eleifend. Arcu cursus euismod quis viverra nibh cras. Dui sapien eget mi proin sed libero. Sit amet consectetur adipiscing elit pellentesque habitant. Morbi tincidunt ornare massa eget egestas. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Risus commodo viverra maecenas accumsan lacus vel.
    
    Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Arcu non sodales neque sodales ut etiam sit amet. Ut sem nulla pharetra diam sit amet. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Rutrum quisque non tellus orci ac auctor augue mauris augue. Nunc mi ipsum faucibus vitae aliquet nec. Massa massa ultricies mi quis hendrerit. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Et netus et malesuada fames ac turpis egestas. Tristique nulla aliquet enim tortor at auctor. Habitant morbi tristique senectus et. Lacinia quis vel eros donec ac odio. Non enim praesent elementum facilisis leo vel fringilla est. Gravida quis blandit turpis cursus in hac. Sed risus ultricies tristique nulla aliquet enim tortor. Risus quis varius quam quisque id.
    
    Tellus in hac habitasse platea. Iaculis urna id volutpat lacus. Neque gravida in fermentum et sollicitudin ac orci. Amet aliquam id diam maecenas. Consectetur adipiscing elit pellentesque habitant morbi tristique. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Proin nibh nisl condimentum id venenatis. Varius sit amet mattis vulputate enim nulla aliquet. Gravida rutrum quisque non tellus orci. Semper feugiat nibh sed pulvinar proin gravida. Malesuada proin libero nunc consequat. Aenean et tortor at risus viverra. Ultrices neque ornare aenean euismod elementum nisi quis. At urna condimentum mattis pellentesque id nibh. Tellus mauris a diam maecenas sed enim ut.
    
    Ut consequat semper viverra nam. Auctor augue mauris augue neque. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Tincidunt eget nullam non nisi est sit. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Purus ut faucibus pulvinar elementum integer. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Tristique risus nec feugiat in fermentum posuere. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Semper auctor neque vitae tempus quam pellentesque nec nam. Nunc mattis enim ut tellus.
    
    Amet est placerat in egestas erat imperdiet sed euismod nisi. Malesuada bibendum arcu vitae elementum curabitur. Tortor posuere ac ut consequat semper. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Arcu dictum varius duis at consectetur lorem. Condimentum lacinia quis vel eros donec. Nec feugiat in fermentum posuere urna. Enim diam vulputate ut pharetra sit amet aliquam id. Faucibus turpis in eu mi bibendum neque. Sed felis eget velit aliquet sagittis id consectetur purus. Facilisis magna etiam tempor orci eu lobortis. Eu volutpat odio facilisis mauris. Eros donec ac odio tempor orci dapibus ultrices in. Elit eget gravida cum sociis natoque penatibus. Massa eget egestas purus viverra accumsan in nisl nisi. Tortor condimentum lacinia quis vel. In aliquam sem fringilla ut morbi tincidunt augue interdum.
    
    Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Nunc congue nisi vitae suscipit. Suspendisse ultrices gravida dictum fusce ut. Eget sit amet tellus cras. In ornare quam viverra orci. Nec dui nunc mattis enim ut tellus elementum sagittis. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Feugiat pretium nibh ipsum consequat nisl. Vulputate dignissim suspendisse in est.
    
    Gravida cum sociis natoque penatibus et magnis. Malesuada bibendum arcu vitae elementum curabitur. Ornare massa eget egestas purus viverra accumsan. At tempor commodo ullamcorper a. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Tincidunt id aliquet risus feugiat in ante. Aliquam eleifend mi in nulla posuere sollicitudin. Feugiat scelerisque varius morbi enim nunc faucibus. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Et netus et malesuada fames ac turpis egestas integer. Sed egestas egestas fringilla phasellus faucibus. Hac habitasse platea dictumst quisque sagittis purus sit. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Tellus mauris a diam maecenas. Sit amet nisl purus in mollis nunc.
    
    Sed sed risus pretium quam. Elementum integer enim neque volutpat. Bibendum at varius vel pharetra vel. Adipiscing bibendum est ultricies integer quis auctor elit sed. Sed nisi lacus sed viverra tellus in hac habitasse platea. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Quam id leo in vitae. Facilisi morbi tempus iaculis urna id volutpat lacus. Ultrices gravida dictum fusce ut placerat orci. Quis varius quam quisque id diam vel quam elementum pulvinar. Dis parturient montes nascetur ridiculus mus. At quis risus sed vulputate odio. Metus vulputate eu scelerisque felis imperdiet proin. Felis eget nunc lobortis mattis.
    
    Ligula ullamcorper malesuada proin libero nunc consequat. Lorem ipsum dolor sit amet consectetur adipiscing elit. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Cras adipiscing enim eu turpis egestas pretium. Arcu dui vivamus arcu felis. Pellentesque dignissim enim sit amet. Tincidunt augue interdum velit euismod. Ac placerat vestibulum lectus mauris ultrices eros in. Turpis massa tincidunt dui ut ornare lectus sit amet est. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis.
    
    Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Congue nisi vitae suscipit tellus. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sed libero enim sed faucibus. Orci eu lobortis elementum nibh tellus. Suspendisse sed nisi lacus sed viverra. Blandit cursus risus at ultrices. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Nulla facilisi cras fermentum odio eu feugiat. Odio ut sem nulla pharetra diam sit amet nisl. Amet dictum sit amet justo. Volutpat lacus laoreet non curabitur. Lorem ipsum dolor sit amet consectetur adipiscing. Purus sit amet volutpat consequat mauris nunc congue nisi. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec.
    
    Ipsum consequat nisl vel pretium. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Id leo in vitae turpis massa sed elementum tempus. Morbi tincidunt ornare massa eget egestas purus viverra accumsan. Massa placerat duis ultricies lacus sed turpis tincidunt. Velit ut tortor pretium viverra suspendisse potenti nullam. Enim eu turpis egestas pretium aenean. Nisi est sit amet facilisis magna. Curabitur gravida arcu ac tortor. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Non curabitur gravida arcu ac tortor dignissim convallis. Tellus mauris a diam maecenas sed enim ut. Adipiscing diam donec adipiscing tristique risus nec.
    
    Vitae suscipit tellus mauris a diam maecenas sed enim ut. Risus feugiat in ante metus. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Duis ut diam quam nulla porttitor. Risus ultricies tristique nulla aliquet enim tortor at auctor. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Elementum curabitur vitae nunc sed velit. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Magna fermentum iaculis eu non diam phasellus vestibulum. Commodo elit at imperdiet dui accumsan sit amet.
    
    Aliquam ut porttitor leo a. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Malesuada fames ac turpis egestas. Condimentum vitae sapien pellentesque habitant morbi tristique. Ut etiam sit amet nisl purus in. Adipiscing enim eu turpis egestas pretium aenean pharetra. Dignissim convallis aenean et tortor. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Nam at lectus urna duis convallis convallis tellus id. Eget sit amet tellus cras adipiscing enim. Mi proin sed libero enim. Varius morbi enim nunc faucibus a pellentesque sit. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in.
    
    Cras semper auctor neque vitae. In ante metus dictum at tempor commodo. Turpis in eu mi bibendum neque egestas congue quisque egestas. Purus in mollis nunc sed id semper risus. Eget dolor morbi non arcu risus quis. Id diam vel quam elementum pulvinar etiam non quam. A lacus vestibulum sed arcu non odio euismod. Malesuada nunc vel risus commodo. Lectus mauris ultrices eros in cursus turpis massa. Nisl tincidunt eget nullam non nisi est sit amet facilisis.
    
    Purus sit amet volutpat consequat mauris. Lacus viverra vitae congue eu consequat ac. Tincidunt praesent semper feugiat nibh. Velit dignissim sodales ut eu sem integer. Euismod elementum nisi quis eleifend. Velit dignissim sodales ut eu sem integer. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Aliquam vestibulum morbi blandit cursus risus at ultrices mi tempus. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Sed libero enim sed faucibus turpis in eu mi. Nisl nisi scelerisque eu ultrices vitae auctor eu. Erat velit scelerisque in dictum. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
    
    Viverra orci sagittis eu volutpat odio facilisis mauris. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Nisl condimentum id venenatis a condimentum. Eget duis at tellus at urna condimentum mattis pellentesque. Sed faucibus turpis in eu. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Pretium aenean pharetra magna ac placerat vestibulum.
    
    Urna nunc id cursus metus aliquam eleifend mi. Tortor condimentum lacinia quis vel eros. Odio euismod lacinia at quis risus sed vulputate odio. Turpis tincidunt id aliquet risus feugiat. Scelerisque mauris pellentesque pulvinar pellentesque. Mattis ullamcorper velit sed ullamcorper. Eget velit aliquet sagittis id consectetur purus. Enim neque volutpat ac tincidunt vitae semper. Sed risus pretium quam vulputate dignissim suspendisse in. Magnis dis parturient montes nascetur ridiculus. Commodo quis imperdiet massa tincidunt. Viverra vitae congue eu consequat ac felis donec. Et molestie ac feugiat sed. In est ante in nibh mauris cursus mattis molestie a. Ut morbi tincidunt augue interdum velit euismod. Risus ultricies tristique nulla aliquet enim tortor at auctor urna.
    
    Enim nunc faucibus a pellentesque. Dui id ornare arcu odio ut sem. Turpis egestas pretium aenean pharetra magna. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Facilisi etiam dignissim diam quis enim lobortis. Et netus et malesuada fames ac turpis egestas. Egestas quis ipsum suspendisse ultrices. Nam libero justo laoreet sit amet. Congue quisque egestas diam in arcu. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Feugiat in ante metus dictum at tempor commodo ullamcorper. Convallis aenean et tortor at risus viverra adipiscing at in. Sapien et ligula ullamcorper malesuada proin. Diam sollicitudin tempor id eu nisl.
    
    Auctor elit sed vulputate mi sit. At consectetur lorem donec massa sapien faucibus et molestie ac. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Quam nulla porttitor massa id neque aliquam. Orci dapibus ultrices in iaculis nunc sed augue. Risus ultricies tristique nulla aliquet enim tortor at auctor. Integer vitae justo eget magna fermentum iaculis eu. Aliquam sem fringilla ut morbi tincidunt augue. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Urna porttitor rhoncus dolor purus non enim praesent elementum. Varius quam quisque id diam. Leo in vitae turpis massa sed elementum tempus. Pellentesque elit ullamcorper dignissim cras. Sed velit dignissim sodales ut eu sem integer vitae justo. Id volutpat lacus laoreet non curabitur gravida arcu ac.
    
    Purus non enim praesent elementum. Egestas diam in arcu cursus euismod quis viverra. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Amet purus gravida quis blandit turpis cursus. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Scelerisque felis imperdiet proin fermentum leo vel. Faucibus a pellentesque sit amet porttitor eget dolor. At lectus urna duis convallis convallis tellus id. Varius duis at consectetur lorem donec massa sapien faucibus et. Sed turpis tincidunt id aliquet risus feugiat in. Vitae semper quis lectus nulla at volutpat diam. Tristique senectus et netus et. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Sed turpis tincidunt id aliquet risus. Nunc sed velit dignissim sodales ut eu sem. Nibh venenatis cras sed felis eget. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
    
    Nec tincidunt praesent semper feugiat nibh sed pulvinar. Sollicitudin tempor id eu nisl nunc. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Mi sit amet mauris commodo quis. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Eget gravida cum sociis natoque penatibus et magnis. Odio facilisis mauris sit amet massa vitae tortor. Id interdum velit laoreet id donec ultrices. Vestibulum lectus mauris ultrices eros. In hac habitasse platea dictumst quisque sagittis purus sit. Ac auctor augue mauris augue neque gravida. Maecenas volutpat blandit aliquam etiam erat velit. Rhoncus dolor purus non enim praesent elementum facilisis leo. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Enim lobortis scelerisque fermentum dui faucibus in. Sed sed risus pretium quam vulputate dignissim suspendisse. Quis blandit turpis cursus in hac habitasse platea dictumst.
    
    Habitant morbi tristique senectus et netus. Sit amet consectetur adipiscing elit. Cursus sit amet dictum sit amet. Velit ut tortor pretium viverra suspendisse potenti. Nullam vehicula ipsum a arcu cursus. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi sit amet mauris commodo quis imperdiet massa. In ornare quam viverra orci sagittis eu volutpat odio. Eget nunc lobortis mattis aliquam. Sociis natoque penatibus et magnis dis parturient montes nascetur. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Est sit amet facilisis magna etiam tempor orci eu. Est placerat in egestas erat imperdiet sed euismod nisi porta. Mi in nulla posuere sollicitudin. Cursus vitae congue mauris rhoncus aenean vel elit.
    
    Sed augue lacus viverra vitae congue eu consequat ac. Pellentesque nec nam aliquam sem et tortor consequat id. Semper risus in hendrerit gravida rutrum quisque non tellus. Lacus sed turpis tincidunt id aliquet risus. Velit ut tortor pretium viverra. Eget dolor morbi non arcu risus quis varius quam quisque. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Nisi est sit amet facilisis magna etiam tempor orci eu. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Tristique nulla aliquet enim tortor at auctor. Malesuada proin libero nunc consequat. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Pharetra massa massa ultricies mi quis hendrerit. Quis risus sed vulputate odio ut. Elementum pulvinar etiam non quam lacus. Interdum consectetur libero id faucibus. Magna sit amet purus gravida quis.
    
    Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Viverra aliquet eget sit amet. Nisi vitae suscipit tellus mauris. Suspendisse potenti nullam ac tortor vitae. Mauris ultrices eros in cursus turpis massa. Tellus cras adipiscing enim eu. Gravida rutrum quisque non tellus orci. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Enim neque volutpat ac tincidunt vitae semper. Nibh sit amet commodo nulla. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Mi sit amet mauris commodo quis. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Urna porttitor rhoncus dolor purus. Maecenas pharetra convallis posuere morbi leo urna molestie. Et molestie ac feugiat sed lectus. Netus et malesuada fames ac turpis egestas.
    
    Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. At tellus at urna condimentum. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Arcu ac tortor dignissim convallis. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Ullamcorper sit amet risus nullam eget felis. Amet commodo nulla facilisi nullam vehicula. Amet massa vitae tortor condimentum lacinia quis vel eros. Congue quisque egestas diam in arcu cursus euismod. Est sit amet facilisis magna etiam tempor orci eu. Orci dapibus ultrices in iaculis nunc sed augue.
    
    Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Bibendum enim facilisis gravida neque convallis. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Massa placerat duis ultricies lacus. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Pulvinar elementum integer enim neque volutpat. Faucibus ornare suspendisse sed nisi lacus sed. Vestibulum sed arcu non odio euismod. Egestas tellus rutrum tellus pellentesque eu tincidunt. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Sapien faucibus et molestie ac feugiat sed. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Blandit volutpat maecenas volutpat blandit.
    
    Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Arcu non sodales neque sodales ut etiam sit. Orci ac auctor augue mauris augue neque gravida in. Tortor condimentum lacinia quis vel eros donec ac. Sit amet tellus cras adipiscing. Velit sed ullamcorper morbi tincidunt ornare. Mauris cursus mattis molestie a iaculis at. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Maecenas sed enim ut sem viverra aliquet eget. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Eros donec ac odio tempor. Tincidunt eget nullam non nisi est sit amet facilisis. Sit amet justo donec enim. Sit amet purus gravida quis blandit. Vel facilisis volutpat est velit egestas dui id ornare arcu. Hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Amet commodo nulla facilisi nullam vehicula ipsum a.
    
    Turpis egestas maecenas pharetra convallis posuere morbi leo. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Neque convallis a cras semper auctor neque vitae tempus quam. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Diam ut venenatis tellus in metus. Facilisis magna etiam tempor orci. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Integer vitae justo eget magna fermentum iaculis eu. Lacus suspendisse faucibus interdum posuere. Netus et malesuada fames ac. Amet aliquam id diam maecenas ultricies mi. Nibh ipsum consequat nisl vel pretium. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Diam volutpat commodo sed egestas.
    
    Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Id volutpat lacus laoreet non curabitur. Placerat duis ultricies lacus sed turpis tincidunt. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Eu mi bibendum neque egestas congue quisque egestas. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Ullamcorper malesuada proin libero nunc consequat interdum. Gravida dictum fusce ut placerat orci nulla pellentesque. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus.
    
    Tortor dignissim convallis aenean et tortor at risus. Enim facilisis gravida neque convallis a cras semper auctor neque. Interdum posuere lorem ipsum dolor sit amet. Ultrices tincidunt arcu non sodales neque. Sed euismod nisi porta lorem mollis. Eget dolor morbi non arcu risus. Molestie ac feugiat sed lectus. Integer eget aliquet nibh praesent tristique magna sit. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. In hac habitasse platea dictumst.
    
    Faucibus interdum posuere lorem ipsum dolor sit amet. Augue lacus viverra vitae congue eu consequat ac. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Nulla porttitor massa id neque. Augue neque gravida in fermentum et sollicitudin ac. Quis auctor elit sed vulputate mi sit. Lorem donec massa sapien faucibus et molestie. Odio euismod lacinia at quis risus. Egestas diam in arcu cursus euismod quis viverra nibh cras. Amet cursus sit amet dictum sit amet justo donec enim. Non arcu risus quis varius quam quisque. Quis ipsum suspendisse ultrices gravida dictum fusce. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Nulla pellentesque dignissim enim sit amet venenatis urna. Varius quam quisque id diam vel. Facilisi nullam vehicula ipsum a arcu cursus vitae.
    
    Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Aliquet eget sit amet tellus cras adipiscing enim eu. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Lorem mollis aliquam ut porttitor leo a diam. Donec et odio pellentesque diam. Tortor at risus viverra adipiscing at in. Blandit aliquam etiam erat velit scelerisque in dictum non. Lectus proin nibh nisl condimentum id venenatis a condimentum vitae. Hendrerit gravida rutrum quisque non tellus orci. Dolor purus non enim praesent elementum facilisis leo vel. Maecenas pharetra convallis posuere morbi. Scelerisque varius morbi enim nunc faucibus a. Sit amet aliquam id diam maecenas. Sagittis id consectetur purus ut faucibus pulvinar. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc.
    
    Ut etiam sit amet nisl purus. Ipsum a arcu cursus vitae congue. Turpis egestas pretium aenean pharetra magna ac. Mollis aliquam ut porttitor leo. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Vitae suscipit tellus mauris a diam. Egestas dui id ornare arcu odio ut sem. Est sit amet facilisis magna etiam tempor orci eu lobortis. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. In mollis nunc sed id semper risus in hendrerit gravida.
    
    Purus sit amet volutpat consequat mauris nunc congue. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Malesuada bibendum arcu vitae elementum curabitur vitae. Amet porttitor eget dolor morbi non arcu risus quis. Vitae et leo duis ut. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Metus aliquam eleifend mi in. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Laoreet sit amet cursus sit amet dictum sit amet justo. Massa massa ultricies mi quis hendrerit. Sit amet tellus cras adipiscing enim eu turpis. Ut venenatis tellus in metus vulputate eu scelerisque felis. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Aliquet nec ullamcorper sit amet. Sed ullamcorper morbi tincidunt ornare. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra.
    
    Tellus elementum sagittis vitae et leo. Diam quam nulla porttitor massa id neque aliquam vestibulum. Eu scelerisque felis imperdiet proin. Pulvinar etiam non quam lacus suspendisse faucibus interdum. Egestas erat imperdiet sed euismod. Rhoncus est pellentesque elit ullamcorper dignissim. In hendrerit gravida rutrum quisque. Faucibus scelerisque eleifend donec pretium vulputate sapien. Non blandit massa enim nec dui nunc mattis enim. Sodales ut etiam sit amet nisl purus. Ipsum dolor sit amet consectetur adipiscing. Tincidunt augue interdum velit euismod in pellentesque massa. Ornare suspendisse sed nisi lacus sed viverra tellus in. Libero id faucibus nisl tincidunt eget nullam non nisi est. Urna duis convallis convallis tellus. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Malesuada nunc vel risus commodo viverra. Arcu vitae elementum curabitur vitae.
    
    Mattis rhoncus urna neque viverra justo nec ultrices. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Quam pellentesque nec nam aliquam sem. Tristique senectus et netus et malesuada fames. Ultrices vitae auctor eu augue ut lectus arcu bibendum. Enim diam vulputate ut pharetra sit amet. Mattis aliquam faucibus purus in. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Sagittis orci a scelerisque purus. Cursus mattis molestie a iaculis. Sed risus pretium quam vulputate dignissim suspendisse. Faucibus scelerisque eleifend donec pretium.
    
    Gravida cum sociis natoque penatibus et magnis dis parturient montes. Mattis nunc sed blandit libero volutpat sed cras ornare. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Mauris nunc congue nisi vitae suscipit tellus mauris. Facilisis magna etiam tempor orci eu lobortis elementum. Netus et malesuada fames ac turpis egestas integer. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Quam quisque id diam vel quam elementum pulvinar. Suscipit tellus mauris a diam maecenas sed. Pellentesque adipiscing commodo elit at imperdiet. Ultricies mi eget mauris pharetra. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Nullam non nisi est sit amet. Nunc faucibus a pellentesque sit amet porttitor eget. Magna ac placerat vestibulum lectus mauris ultrices eros in. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Congue eu consequat ac felis donec et odio pellentesque.
    
    A pellentesque sit amet porttitor. Mi bibendum neque egestas congue. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Arcu bibendum at varius vel pharetra. Tristique sollicitudin nibh sit amet commodo. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Dui faucibus in ornare quam. Habitant morbi tristique senectus et netus et malesuada. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Dolor purus non enim praesent elementum facilisis leo vel. Convallis posuere morbi leo urna molestie.
    
    At quis risus sed vulputate. Tristique magna sit amet purus. A arcu cursus vitae congue mauris rhoncus aenean. Maecenas sed enim ut sem viverra aliquet eget. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Porttitor eget dolor morbi non arcu. Quam viverra orci sagittis eu volutpat odio. Egestas integer eget aliquet nibh praesent. Tempus egestas sed sed risus pretium. Amet tellus cras adipiscing enim eu turpis egestas.
    
    Tortor consequat id porta nibh venenatis cras sed felis. Sed adipiscing diam donec adipiscing tristique risus nec feugiat in. In hac habitasse platea dictumst vestibulum. Egestas dui id ornare arcu odio ut. Gravida neque convallis a cras semper. Ut morbi tincidunt augue interdum. Magna ac placerat vestibulum lectus mauris ultrices eros. Pharetra diam sit amet nisl suscipit. Est ultricies integer quis auctor. Velit dignissim sodales ut eu sem integer vitae. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Tortor id aliquet lectus proin. Nibh mauris cursus mattis molestie a iaculis at. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
    
    Tincidunt dui ut ornare lectus sit amet est placerat. Commodo odio aenean sed adipiscing diam donec adipiscing. Pulvinar etiam non quam lacus. Auctor elit sed vulputate mi sit amet mauris commodo quis. Sagittis purus sit amet volutpat consequat mauris. Sed faucibus turpis in eu mi. Eget arcu dictum varius duis at consectetur. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Eu facilisis sed odio morbi quis commodo odio aenean. Sit amet nisl purus in. Imperdiet sed euismod nisi porta lorem mollis. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Sem viverra aliquet eget sit amet tellus cras. Convallis tellus id interdum velit laoreet. Eu mi bibendum neque egestas congue quisque. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Vivamus arcu felis bibendum ut tristique et egestas quis.
    
    Vel risus commodo viverra maecenas. Arcu ac tortor dignissim convallis aenean et tortor at risus. Enim sit amet venenatis urna cursus eget nunc scelerisque. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Turpis massa tincidunt dui ut ornare lectus sit. Quam elementum pulvinar etiam non quam. Eget aliquet nibh praesent tristique magna. Morbi tristique senectus et netus et. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Metus aliquam eleifend mi in nulla posuere sollicitudin.
    
    Pellentesque id nibh tortor id aliquet. Sed felis eget velit aliquet sagittis id consectetur. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Massa sapien faucibus et molestie ac. Blandit massa enim nec dui nunc mattis enim ut tellus. Vitae tortor condimentum lacinia quis vel eros donec ac. Eu consequat ac felis donec et odio pellentesque. Ipsum suspendisse ultrices gravida dictum fusce ut placerat. Ut placerat orci nulla pellentesque dignissim enim sit. Dignissim cras tincidunt lobortis feugiat. In mollis nunc sed id semper risus in hendrerit. Lobortis elementum nibh tellus molestie nunc non. Consequat ac felis donec et odio pellentesque diam volutpat. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Amet justo donec enim diam vulputate ut pharetra sit amet. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Sed elementum tempus egestas sed sed risus pretium quam.
    
    Ut tellus elementum sagittis vitae. Elementum eu facilisis sed odio morbi. Risus pretium quam vulputate dignissim suspendisse. Ultricies lacus sed turpis tincidunt id aliquet risus. Ut faucibus pulvinar elementum integer. At auctor urna nunc id cursus. Faucibus interdum posuere lorem ipsum dolor sit amet. Id aliquet risus feugiat in ante metus. Accumsan lacus vel facilisis volutpat est. Sit amet mauris commodo quis.
    
    Diam maecenas sed enim ut sem viverra. Eleifend quam adipiscing vitae proin. Facilisis leo vel fringilla est ullamcorper. Elit sed vulputate mi sit amet. Leo a diam sollicitudin tempor id eu nisl. Diam sollicitudin tempor id eu nisl. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Vitae sapien pellentesque habitant morbi tristique senectus et. Auctor eu augue ut lectus arcu bibendum at varius vel. Nec feugiat nisl pretium fusce id velit. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Augue ut lectus arcu bibendum at varius vel pharetra vel. Tristique nulla aliquet enim tortor at auctor. Risus at ultrices mi tempus. Facilisis leo vel fringilla est ullamcorper.
    
    Nisi lacus sed viverra tellus in hac habitasse. Bibendum ut tristique et egestas. Dignissim enim sit amet venenatis. Sed risus ultricies tristique nulla aliquet. Viverra tellus in hac habitasse platea dictumst vestibulum. Gravida rutrum quisque non tellus orci ac auctor augue. Eget est lorem ipsum dolor sit amet consectetur. Tincidunt vitae semper quis lectus nulla at volutpat diam. A diam sollicitudin tempor id eu nisl. Tellus molestie nunc non blandit massa enim. Vulputate dignissim suspendisse in est ante in nibh mauris. Sagittis purus sit amet volutpat consequat. Pellentesque massa placerat duis ultricies lacus. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Nullam eget felis eget nunc lobortis mattis. Velit egestas dui id ornare arcu odio ut sem nulla. A lacus vestibulum sed arcu non odio euismod lacinia at. Risus pretium quam vulputate dignissim suspendisse in est ante. Enim sed faucibus turpis in eu mi bibendum.
    
    Amet cursus sit amet dictum. Id nibh tortor id aliquet lectus proin. Pharetra diam sit amet nisl suscipit adipiscing. Cum sociis natoque penatibus et magnis dis parturient montes. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Et malesuada fames ac turpis egestas integer eget. Quis lectus nulla at volutpat diam. Tristique magna sit amet purus. Neque gravida in fermentum et sollicitudin ac orci. Bibendum at varius vel pharetra vel turpis nunc. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Auctor elit sed vulputate mi sit. At tellus at urna condimentum mattis pellentesque id nibh tortor.
    
    Aliquam ut porttitor leo a diam sollicitudin tempor id. Bibendum neque egestas congue quisque egestas diam in arcu. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ut ornare lectus sit amet est placerat in. Malesuada fames ac turpis egestas. Proin fermentum leo vel orci porta non. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Non blandit massa enim nec dui nunc. Eget sit amet tellus cras adipiscing. Et tortor at risus viverra adipiscing at in. Viverra tellus in hac habitasse platea. Sed turpis tincidunt id aliquet risus. Fames ac turpis egestas sed tempus urna et pharetra. Risus quis varius quam quisque id. Aliquam etiam erat velit scelerisque in. Neque laoreet suspendisse interdum consectetur libero id faucibus. Id faucibus nisl tincidunt eget nullam. Leo vel orci porta non pulvinar neque.
    
    Felis eget nunc lobortis mattis aliquam faucibus. Amet venenatis urna cursus eget nunc scelerisque viverra. Ut eu sem integer vitae justo eget magna. Viverra justo nec ultrices dui sapien eget mi. At varius vel pharetra vel turpis nunc eget. Sed enim ut sem viverra aliquet eget. In hac habitasse platea dictumst quisque sagittis purus sit. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Ac turpis egestas maecenas pharetra convallis. Dolor purus non enim praesent elementum. Erat velit scelerisque in dictum non consectetur a erat nam. In hendrerit gravida rutrum quisque non tellus orci. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Massa tincidunt dui ut ornare lectus sit amet. Donec pretium vulputate sapien nec sagittis. Sed vulputate mi sit amet mauris commodo quis. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Diam quam nulla porttitor massa id.`
    );}
    }

    const useTermService = new UseTermService();
    Object.freeze(useTermService);

    export default useTermService;
